import { EventPhase, PhaseMetadata } from './types';

export const PHASE_CONFIG: Record<EventPhase, PhaseMetadata> = {
  LANDING: {
    id: 'LANDING',
    roundNumber: null,
    roundTitle: 'Welcome to The Dev House',
    subPhaseTitle: 'System Initialization',
    description: 'Teams enter the house. The surveillance grid is active.',
    nextPhase: 'LOGIN',
    isTimed: false,
    participantRoute: '/',
  },
  LOGIN: {
    id: 'LOGIN',
    roundNumber: null,
    roundTitle: 'Authentication',
    subPhaseTitle: 'Team Check-in',
    description: 'Enter your house access credentials issued by the control room.',
    nextPhase: 'ROUND_1_ACTIVE',
    isTimed: false,
    participantRoute: '/login',
  },
  ROUND_1_ACTIVE: {
    id: 'ROUND_1_ACTIVE',
    roundNumber: 1,
    roundTitle: 'Round 1: Rapid Task Challenge',
    subPhaseTitle: 'Task In Progress',
    description: 'Teams must solve and submit the algorithmic & system task before the clock hits zero.',
    nextPhase: 'ROUND_1_RESULTS',
    isTimed: true,
    participantRoute: '/round-1',
  },
  ROUND_1_RESULTS: {
    id: 'ROUND_1_RESULTS',
    roundNumber: 1,
    roundTitle: 'Round 1: Tally & Standings',
    subPhaseTitle: 'Points Confirmed',
    description: 'Round 1 points locked. Leaderboard updated.',
    nextPhase: 'ROUND_2_CAPTAINCY',
    isTimed: false,
    participantRoute: '/dashboard',
  },
  ROUND_2_CAPTAINCY: {
    id: 'ROUND_2_CAPTAINCY',
    roundNumber: 2,
    roundTitle: 'Round 2: Captaincy Battle',
    subPhaseTitle: 'Contenders Duel',
    description: 'Top contending teams fight for house captaincy and tactical immunity advantage.',
    nextPhase: 'ROUND_2_NOMINATIONS',
    isTimed: true,
    participantRoute: '/round-2-captaincy',
  },
  ROUND_2_NOMINATIONS: {
    id: 'ROUND_2_NOMINATIONS',
    roundNumber: 2,
    roundTitle: 'Round 2: Nominations',
    subPhaseTitle: 'The House Decides',
    description: 'Nominated teams are designated for risk of eviction.',
    nextPhase: 'ROUND_2_SECRET_TASK',
    isTimed: false,
    participantRoute: '/dashboard',
  },
  ROUND_2_SECRET_TASK: {
    id: 'ROUND_2_SECRET_TASK',
    roundNumber: 2,
    roundTitle: 'Round 2: Classified Missions',
    subPhaseTitle: 'Secret Protocols Active',
    description: 'Special missions issued to first, middle, and last ranked teams.',
    nextPhase: 'ROUND_3_IMMUNITY',
    isTimed: true,
    participantRoute: '/dashboard',
  },
  ROUND_3_IMMUNITY: {
    id: 'ROUND_3_IMMUNITY',
    roundNumber: 3,
    roundTitle: 'Round 3: Immunity Challenge',
    subPhaseTitle: 'Survive the Cut',
    description: 'Nominated teams paired with safe allies clash for survival.',
    nextPhase: 'ROUND_3_VOTING',
    isTimed: true,
    participantRoute: '/dashboard',
  },
  ROUND_3_VOTING: {
    id: 'ROUND_3_VOTING',
    roundNumber: 3,
    roundTitle: 'Round 3: House Vote',
    subPhaseTitle: 'Eviction Ballot Open',
    description: 'Voting window is open. Cast your verdict.',
    nextPhase: 'ROUND_3_EVICTION_REVEAL',
    isTimed: true,
    participantRoute: '/dashboard',
  },
  ROUND_3_EVICTION_REVEAL: {
    id: 'ROUND_3_EVICTION_REVEAL',
    roundNumber: 3,
    roundTitle: 'Round 3: Eviction Verdict',
    subPhaseTitle: 'The Eye Has Spoken',
    description: 'Live dramatic eviction reveal. Eliminated teams leave the house.',
    nextPhase: 'ROUND_4_FEATURES_REVEALED',
    isTimed: false,
    participantRoute: '/dashboard',
  },
  ROUND_4_FEATURES_REVEALED: {
    id: 'ROUND_4_FEATURES_REVEALED',
    roundNumber: 4,
    roundTitle: 'Round 4: The Finale Build',
    subPhaseTitle: 'Hidden Specs Unlocked',
    description: 'Surviving teams build against live hidden feature requirements.',
    nextPhase: 'ROUND_4_SUBMISSION',
    isTimed: true,
    participantRoute: '/dashboard',
  },
  ROUND_4_SUBMISSION: {
    id: 'ROUND_4_SUBMISSION',
    roundNumber: 4,
    roundTitle: 'Round 4: Final Submission',
    subPhaseTitle: 'Code Freeze Imminent',
    description: 'Submit your live deployment URL and repository link for jury inspection.',
    nextPhase: 'ROUND_4_JUDGING',
    isTimed: true,
    participantRoute: '/dashboard',
  },
  ROUND_4_JUDGING: {
    id: 'ROUND_4_JUDGING',
    roundNumber: 4,
    roundTitle: 'Round 4: Jury Evaluation',
    subPhaseTitle: 'Auditing Builds',
    description: 'Judges are testing feature specifications and deducting out-of-scope penalties.',
    nextPhase: 'FINAL_RESULTS',
    isTimed: false,
    participantRoute: '/dashboard',
  },
  FINAL_RESULTS: {
    id: 'FINAL_RESULTS',
    roundNumber: 4,
    roundTitle: 'The Dev House: Grand Finale',
    subPhaseTitle: 'Champions Crowned',
    description: 'The final surviving champion of The Dev House is revealed.',
    nextPhase: null,
    isTimed: false,
    participantRoute: '/dashboard',
  },
};

export const ORDERED_PHASES: EventPhase[] = [
  'LANDING',
  'LOGIN',
  'ROUND_1_ACTIVE',
  'ROUND_1_RESULTS',
  'ROUND_2_CAPTAINCY',
  'ROUND_2_NOMINATIONS',
  'ROUND_2_SECRET_TASK',
  'ROUND_3_IMMUNITY',
  'ROUND_3_VOTING',
  'ROUND_3_EVICTION_REVEAL',
  'ROUND_4_FEATURES_REVEALED',
  'ROUND_4_SUBMISSION',
  'ROUND_4_JUDGING',
  'FINAL_RESULTS',
];
