export enum EventPhase {
  LANDING = 'LANDING',
  LOGIN = 'LOGIN',
  ROUND_1_ACTIVE = 'ROUND_1_ACTIVE',
  ROUND_1_RESULTS = 'ROUND_1_RESULTS',
  ROUND_2_CAPTAINCY = 'ROUND_2_CAPTAINCY',
  ROUND_2_NOMINATIONS = 'ROUND_2_NOMINATIONS',
  ROUND_2_SECRET_TASK = 'ROUND_2_SECRET_TASK',
  ROUND_3_IMMUNITY = 'ROUND_3_IMMUNITY',
  ROUND_3_VOTING_OPEN = 'ROUND_3_VOTING_OPEN',
  ROUND_3_VOTING_CLOSED = 'ROUND_3_VOTING_CLOSED',
  ROUND_3_EVICTION_REVEAL = 'ROUND_3_EVICTION_REVEAL',
  ROUND_4_FEATURES_REVEALED = 'ROUND_4_FEATURES_REVEALED',
  ROUND_4_SUBMISSION = 'ROUND_4_SUBMISSION',
  ROUND_4_JUDGING = 'ROUND_4_JUDGING',
  FINAL_RESULTS = 'FINAL_RESULTS'
}

export type VoterRole = 'PARTICIPANT' | 'JUDGE' | 'AUDIENCE';

export interface Team {
  id: string;
  name: string;
  members: string[];
}
